const categorySelectData = {
  wrapperSelector: '#select-wrapper-category',
  name: 'category',
  id: 'category',
  classNames: [''],
  placeholder: 'Например, Личный опыт',
  placeholderColor: '#CCCCCC',
  mainColor: '#3D3D3D',
  eventName: 'setCustomSelectValue',
  options: [],
  isRequired: true,
}

const categories = [
    { name: 'Безопасность бизнеса', value: 'bezopasnost-biznesa' },
    { name: 'Бизнес с нуля', value: 'biznes-s-nulya' },
    { name: 'Бизнес-ланч', value: 'biznes-lanch' },
    { name: 'Блоги компаний', value: 'blogi-kompanij' },
    { name: 'Бухгалтерия', value: 'buhgalteriya' },
    { name: 'Вакансии', value: 'vakansii' },
    { name: 'Вопрос-ответ', value: 'voprosy-otvety' },
    { name: 'Госзакупки', value: 'goszakupki' },
    { name: 'Дневники', value: 'dnevniki' },
    { name: 'Документы', value: 'dokumenty' },
    { name: 'Жизнь вне работы', value: 'lifestyle' },
    { name: 'Законы', value: 'laws' },
    { name: 'Инвестиции для бизнеса', value: 'investicii' },
    { name: 'Индивидуальные Предприниматели', value: 'ip' },
    { name: 'Исследования', value: 'data' },
    { name: 'Истории', value: 'story' },
    { name: 'Калькуляторы', value: 'calculators' },
    { name: 'Кейсы', value: 'kejsy-istorii' },
    { name: 'Кейсы', value: 'cases' },
    { name: 'Книги для бизнеса', value: 'knigi-dlya-biznesa' },
    { name: 'Личный опыт', value: 'lichnyj-opyt' },
    { name: 'Льготы', value: 'lgoty' },
    { name: 'Люди в бизнесе', value: 'people' },
    { name: 'Маркетинг', value: 'marketing' },
    { name: 'Мероприятия', value: 'meropriyatiya' },
    { name: 'Новости', value: 'novosti' },
    { name: 'ООО', value: 'ooo' },
    { name: 'От первого лица', value: 'mneniya' },
    { name: 'Продажи', value: 'prodazhi' },
    { name: 'Продукты', value: 'produkty' },
    { name: 'Пульс', value: 'pulse' },
    { name: 'Развитие бизнеса', value: 'razvitie' },
    { name: 'Реалити-шоу', value: 'realiti-shou' },
    { name: 'Самозанятые', value: 'samozanyatye' },
    { name: 'Сотрудники', value: 'sotrudniki' },
    { name: 'Справочник предпринимателя', value: 'glossarij' },
    { name: 'Трансляции', value: 'translyatsii' },
    { name: 'Тренды', value: 'trendy' },
    { name: 'Чек-листы', value: 'chek-listy' }
]
